# KNN 
* Supervised learning
* Used for **classification** and **regression**
* It's used for classification and regression of **known data** where usually the target attribute/variable is known before hand
* KNN doesn’t have a training phase as such. But the prediction of a test observation is done based on the K-Nearest (often euclidean distance) Neighbours (observations) based on weighted averages/votes

## Imports and definitions

In [17]:
import numpy as np
from sklearn import neighbors
import os

In [20]:
def input_dir():
    return os.getcwd() + '/'

def output_dir():
    return os.getcwd() + '/'

## Get data

In [83]:
rdata = open(input_dir() + 'data.csv', 'r+')

### Adjust data

In [81]:
data = []
for line in rdata:
    # Remove \n
    line = line.rstrip()
    data.append([float(x) for x in line.split(',')])
data

[[180.0, 8.0, 3070.0, 1300.0, 3504.0, 120.0],
 [150.0, 8.0, 3500.0, 1650.0, 3693.0, 115.0],
 [180.0, 8.0, 3180.0, 1500.0, 3436.0, 110.0],
 [160.0, 8.0, 3040.0, 1500.0, 3433.0, 120.0],
 [170.0, 8.0, 3020.0, 1400.0, 3449.0, 105.0],
 [150.0, 8.0, 4290.0, 1980.0, 4341.0, 100.0],
 [140.0, 8.0, 4540.0, 2200.0, 4354.0, 90.0],
 [140.0, 8.0, 4400.0, 2150.0, 4312.0, 85.0],
 [140.0, 8.0, 4550.0, 2250.0, 4425.0, 100.0],
 [150.0, 8.0, 3900.0, 1900.0, 3850.0, 85.0],
 [150.0, 8.0, 3830.0, 1700.0, 3563.0, 100.0],
 [140.0, 8.0, 3400.0, 1600.0, 3609.0, 80.0],
 [150.0, 8.0, 4000.0, 1500.0, 3761.0, 95.0],
 [140.0, 8.0, 4550.0, 2250.0, 3086.0, 100.0],
 [240.0, 4.0, 1130.0, 9500.0, 2372.0, 150.0],
 [220.0, 6.0, 1980.0, 9500.0, 2833.0, 155.0],
 [180.0, 6.0, 1990.0, 9700.0, 2774.0, 155.0],
 [210.0, 6.0, 2000.0, 8500.0, 2587.0, 160.0],
 [270.0, 4.0, 9700.0, 8800.0, 2130.0, 145.0],
 [260.0, 4.0, 9700.0, 4600.0, 1835.0, 205.0]]

In [84]:
# for i in range(len(data)):
#     data[i] = [float(x) for x in data[i]]

data = np.array(data)
X = data[:,0:-1]
Y = data[:,-1]

print (X)
print (Y)

[[1.800e+02 8.000e+00 3.070e+03 1.300e+03 3.504e+03]
 [1.500e+02 8.000e+00 3.500e+03 1.650e+03 3.693e+03]
 [1.800e+02 8.000e+00 3.180e+03 1.500e+03 3.436e+03]
 [1.600e+02 8.000e+00 3.040e+03 1.500e+03 3.433e+03]
 [1.700e+02 8.000e+00 3.020e+03 1.400e+03 3.449e+03]
 [1.500e+02 8.000e+00 4.290e+03 1.980e+03 4.341e+03]
 [1.400e+02 8.000e+00 4.540e+03 2.200e+03 4.354e+03]
 [1.400e+02 8.000e+00 4.400e+03 2.150e+03 4.312e+03]
 [1.400e+02 8.000e+00 4.550e+03 2.250e+03 4.425e+03]
 [1.500e+02 8.000e+00 3.900e+03 1.900e+03 3.850e+03]
 [1.500e+02 8.000e+00 3.830e+03 1.700e+03 3.563e+03]
 [1.400e+02 8.000e+00 3.400e+03 1.600e+03 3.609e+03]
 [1.500e+02 8.000e+00 4.000e+03 1.500e+03 3.761e+03]
 [1.400e+02 8.000e+00 4.550e+03 2.250e+03 3.086e+03]
 [2.400e+02 4.000e+00 1.130e+03 9.500e+03 2.372e+03]
 [2.200e+02 6.000e+00 1.980e+03 9.500e+03 2.833e+03]
 [1.800e+02 6.000e+00 1.990e+03 9.700e+03 2.774e+03]
 [2.100e+02 6.000e+00 2.000e+03 8.500e+03 2.587e+03]
 [2.700e+02 4.000e+00 9.700e+03 8.800e+03 2.13

## KNN

In [85]:
n_neighbors = 5
knn = neighbors.KNeighborsRegressor(n_neighbors, weights='distance')
y = knn.fit(X, Y).predict([[245.,4.,9700.,4600.,1835.]])

print (y)

[203.99552692]
